//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkedIn_Accord.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public int Id { get; set; }
        public string LinkedInId { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public string OriginalThinkerLinkedInId { get; set; }
        public string OriginalThinkerName { get; set; }
        public int OriginalThinkerPoints { get; set; }
        public string OriginalThinkerImageUrl { get; set; }
        public string SocialButterflyLinkedInId { get; set; }
        public string SocialButterflyName { get; set; }
        public int SocialButterflyPoints { get; set; }
        public string SocialButterflyImageUrl { get; set; }
        public string DiplomatLinkedInId { get; set; }
        public string DiplomatName { get; set; }
        public int DiplomatPoints { get; set; }
        public string DiplomatImageUrl { get; set; }
        public string DependableLinkedInId { get; set; }
        public string DependableName { get; set; }
        public int DependablePoints { get; set; }
        public string DependableImageUrl { get; set; }
        public string HighAchieverLinkedInId { get; set; }
        public string HighAchieverName { get; set; }
        public int HighAchieverPoints { get; set; }
        public string HighAchieverImageUrl { get; set; }
        public bool Offers { get; set; }
        public bool AgreedTerms { get; set; }
        public int TotalPoints { get; set; }
        public bool PostUpdate { get; set; }
        public string ProfileUrl { get; set; }
    }
}
